# Generated by Django 5.0.3 on 2024-03-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='photo',
            new_name='name',
        ),
    ]
