# Generated by Django 5.0.3 on 2024-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique_for_date='publish'),
        ),
    ]
