# Generated by Django 5.0.3 on 2024-03-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='note',
            index_together={('id', 'slug')},
        ),
    ]
